#+TITLE: llm_chat_plugins/todo

* Make the bot work in groups
** should only activate when the message starts with =@{bot_username}=
*** should strip this prefix from messages when constructing the history

*** have a separate context mode setting for groups =/groupContextMode=
**** for clearing context, check for the separator after striping the prefix activation

*** should add metadata of each message (user id, name, timestamp, forwarded from whom) at the start of each message
Define a variable =metadata_mode=. Default to =ONLY_WHEN_NOT_PRIVATE= which means only add the metadata when used in groups.

* add shortcuts =/sep=, =/replyChain=, =/lastN= for switching context mode directly

* @retired
:PROPERTIES:
:visibility: folded
:END:
** DONE history_util
#+begin_verse
I am now trying to store message ids on new events as a workaround for getting previous messages. But events.NewMessage() seems to filter out the messages the bot itself is sending. How do I also include those?

I am using @client.on(events.NewMessage(outgoing=True)) for catching the messages the bot itself is sending, but it doesn't trigger.
#+end_verse

